config/routes.rb
PhaseZeroPairing::Application.routes.draw do

  get '/' => 'static_pages#home', as: 'home'

  resources :users

  resources :appointments

  resources :sessions, only: [:new, :create]
  get '/logout' => 'sessions#destroy', as: 'logout'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  has_many :user_appointments
  has_many :users, through: :user_appointments
  belongs_to :teacher, class_name: 'User'

  def present_to_user
    "#{self.date.strftime("%A %b %-d, %Y")} at #{self.start_time.strftime("%I:%M%p")}"
  end

  def students
    users.where(:teacher => false)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :user_appointments
  has_many :appointments, through: :user_appointments
end

app/models/user_appointment.rb
class UserAppointment < ActiveRecord::Base
  belongs_to :user
  belongs_to :appointment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def index
    @appointments = Appointment.where(complete: false)
  end

  def show
    @appointment = Appointment.find(params[:id])
  end

  def new
    @appointment = Appointment.new()
  end

  def create
    appointment = Appointment.new(appointment_params)
    appointment.teacher = current_user
    appointment.users << current_user
    if appointment.save
      flash[:success] = 'Pairing session successfully created'
      redirect_to appointment_path(appointment)
    else
      flash[:alert] = appointment.errors.full_messages
      redirect_to new_appointment_path
    end
  end

  def edit
    @appointment = Appointment.find(params[:id])
  end

  def update
    appointment = Appointment.find(params[:id])
    if request.xhr?
      if current_user.teacher
        appointment.complete = true
        appointment.save
        render partial: 'complete'
      else
        appointment.users << current_user
        render partial: 'student', locals: {student: current_user}
      end
    else
      appointment.update(appointment_params)
      redirect_to appointment_path(appointment)
    end
  end

  def destroy
    Appointment.find(params[:id]).destroy
    flash[:alert] = 'Pairing session deleted'
    redirect_to home_path
  end

  private
  def appointment_params
    params.require(:appointment).permit(:start_time, :date, :completed)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if user = User.find_by_email(params[:email])
      if user.authenticate(params[:password])
        session[:user_id] = user.id
        path = home_path
      else
        flash[:alert] = 'password was invalid'
        path = new_session_path
      end
    else
      flash[:alert] = 'email was not found'
      path = new_session_path
    end
    redirect_to path
  end

  def destroy
    session.clear
    redirect_to home_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @appointments = @user.appointments.where(complete: false)
  end

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    user.teacher = params[:user][:teacher] == '1' ? true : false
    if user.save
      flash[:success] = "Thanks #{user.name}. Your account was successfully created"
      session[:user_id] = user.id
      redirect_to home_path
    else
      flash[:warning] = user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def edit
    @user = User.find(params[:id])
    if current_user != @user
      flash[:warning] = "You cannot edit another user's profile"
      redirect_to home_path
    end
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    user.teacher = params[:user][:teacher] == '1' ? true : false
    if user.save
      flash[:success] = "Thanks #{user.name}. Your account successfully updated."
      redirect_to user_path(user)
    else
      flash[:warning] = user.errors.full_messages
      redirect_to edit_user_path(user)
    end
  end

  def delete
    User.find(params[:id]).destroy
    redirect_to home_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appointments/_complete.html.erb
<h4>You just marked this appointment as completed</h4>

app/views/appointments/_form.html.erb
<%= form_for(appointment) do |f| %>
  <div class='form-group'>
    <%= f.label :date, class: 'lead' %>
    <%= f.date_field :date, class: 'lead' %>
  </div>
  <div class='form-group'>
    <%= f.label :start_time, class: 'lead' %>
    <%= f.time_field :start_time, class: 'lead' %>
  </div>
  <div class='form-group'>
    <%= f.submit class: 'btn btn-success btn-large' %>
  </div>

<% end %>

app/views/appointments/_instructions.html.erb
<h4>Instructions for participating in a pairing session</h4>
<ol>
  <li>Navigate to the appropiate google hangout link from the pairing session page</li>
  <% if current_user.teacher %>
    <li>As the leader of a session, create a <%= link_to 'new code document for sharing', 'https://code.stypi.com' %> and share the link wth your students</li>
  <% else %>
    <li>Go to the code document link at <code>https://code.stypi.com</code> that your leader will give you once in the google hangout</li>
  <% end %>
  <li>Choose some practice problems that you would like to cover during the session and go over them together</li>
  <li>If you are the leader for a pairing, make sure to visit the pairing page after and mark the session as completed</li>
</ol>

app/views/appointments/_student.html.erb
<p class'lead'><%= student.name %></p>

app/views/appointments/edit.html.erb
<h1>Edit this pairing session here:</h1>
<p>(please do not edit this pairing within 24 hours of appointment unless no students are signed up yet)</p>

<%= render partial: 'form', locals: {appointment: @appointment} %>

app/views/appointments/index.html.erb
<h1>List of all upcoming pairing sessions (<%= @appointments.count %> upcoming)</h1>
<ul>
  <% @appointments.each do |appointment| %>
    <li>
      <%= link_to appointment.present_to_user, appointment_path(appointment) %>
      <%= "#{appointment.students.count}/2 signed up, guide is #{appointment.teacher.name}" %>
    </li>
  <% end %>
</ul>
<%= render 'instructions' %>

app/views/appointments/new.html.erb
<h1>Create a new pairing session here:</h1>

<%= render partial: 'form', locals: {appointment: @appointment} %>

app/views/appointments/show.html.erb
<h1>Pairing Session page</h1>
<h2>
  <%= "#{@appointment.present_to_user}" %>
</h2>
<div class='teacher_name lead'><h3>Leader for pairing is <%= @appointment.teacher.name %></h3></div>
<div class='pairing_students'>
  <h4>Students currently signed up: (<%= @appointment.students.count %>/2 slots filled)</h4>
  <% @appointment.students.each do |student| %>
    <p class='lead'><%= student.name %></p>
  <% end %>
</div>
<% if @appointment.complete %>
  <h3>This appointment has been completed</h3>
<% else %>
  <% if current_user == @appointment.teacher %>
    <%= link_to 'Edit this Appointment', edit_appointment_path(@appointment), class: 'btn btn-info' %>
    <button class='btn' id='complete_appointment' data-appointment-id='<%= @appointment.id %>'>Mark this appointment as completed</button>
  <% elsif current_user && @appointment.students.count < 2 && !@appointment.users.include?(current_user) %>
    <button class='btn btn-success' id='join_appointment' data-appointment-id='<%= @appointment.id %>'>Add myself to this pairing</button>
  <% end %>

  <%= render 'instructions' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhaseZeroPairing</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class='navbar navbar-default navbar-fixed-top' role='navigation'>
  <div class='collapse navbar-collapse'>
    <ul class='nav navbar-nav'>
      <li><%= link_to 'DBC Phase Zero Pairing', home_path %></li>
      <li><%= link_to 'Members', users_path %></li>
      <li><%= link_to 'Upcoming Pairings', appointments_path %></li>
      <% if current_user %>
        <% if current_user.teacher %>
          <li><%= link_to 'Create Pairing Session', new_appointment_path %></li>
        <% end %>
        <li><%= link_to current_user.name, user_path(current_user) %></li>
        <li><%= link_to 'Logout', logout_path %></li>
      <% else %>
        <li><%= link_to 'Sign In', new_session_path %></li>
        <li><%= link_to 'Create Account', new_user_path %></li>
      <% end %>
    </ul>
  </div>
</nav>
<h4><%= bootstrap_flash %></h2>
<div class='col-md-12'>
<%= yield %>
</div>
</body>
</html>

app/views/static_pages/home.html.erb
<div class='jumbotron'>
  <h1>Phase Zero Guided Pairing</h1>
  <% if current_user %>
    <p>Use the links at the top of the page to navigate the site</p>
  <% else %>
    <p>Create an account or sign in with the buttons above</p>
  <% end %>
  <p>As a teacher or alumnus, you can create pairings that you will lead</p>
  <p>As a student, you can sign up for existing pairings</p>
</div>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <div class='form-group right'>
    <%= f.label :first_name, class: 'lead' %>
    <%= f.text_field :name, placeholder: ' first name', class: 'lead' %>
  </div>
  <div class='form-group right'>
    <%= f.label :email, class: 'lead' %>
    <%= f.text_field :email, placeholder: ' email@email.com', class: 'lead' %>
  </div>
  <div class='form-group right'>
    <%= f.label :password, class: 'lead' %>
    <%= f.password_field :password, class: 'lead' %>
  </div>
  <div class='form-group right'>
    <%= f.label :confirm_password, class: 'lead' %>
    <%= f.password_field :password_confirmation, class: 'lead' %>
  </div>
  <div class='form-group right'>
    <%= f.label :teacher, 'I am a teacher and will lead pairings', class: 'lead' %>
    <%= f.check_box :teacher, class: 'lead' %>
  </div>

  <div class='form-group right'>
    <%= f.submit class: 'btn btn-primary btn-lg' %>
  </div>
  <% end %>

app/views/users/edit.html.erb
<h1>Edit profile here:</h1>
<h2 class='lead'>(leave the password fields blank if you do not wish to change your password</h2>
<div class='jumbotron col-md-6'>
<%= render partial: 'form', locals: {user: @user} %>
</div>

app/views/users/index.html.erb
<h1>List of users</h1>

<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.name, user_path(user) %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Create an account here:</h1>
<div class='jumbotron col-md-6'>
<%= render partial: 'form', locals: {user: @user`} %>
</div>

app/views/users/show.html.erb
<h1>Profile page for <%= @user.name %></h1>

<div class='upcoming_appointments'>
    <h2><%= @user.name %> is scheduled to participate in <%= pluralize(@appointments.count, 'appointment') %></h2>
    <ul>
      <% @appointments.each do |appointment| %>
        <li>
          <%= link_to appointment.present_to_user, appointment_path(appointment) %>
        </li>
      <% end %>
    </ul>
    <h3>In the past <%= @user.name %> has participated in a total of <%= pluralize(@user.appointments.count - @appointments.count, 'appointment') %></h3>
</div>
<% if @user == current_user %>
  <div class='edit_profile'>
    <%= link_to 'Edit My Profile', edit_user_path(@user) %>
  </div>
<% end %>